// server.js for Hostinger Node.js Hosting
const path = require('path');

/**
 * Hostinger Node.js Hosting Entry Point
 * 
 * This file serves as the entry point for Hostinger's Phusion Passenger or Node.js selector.
 * It points to the standalone server generated by Next.js during the build process.
 * 
 * To use this:
 * 1. Run 'npm run build' locally or in CI/CD.
 * 2. Upload the contents of '.next/standalone' to your Hostinger public_html or chosen directory.
 * 3. Upload the contents of '.next/static' to '.next/static' inside that directory.
 * 4. Upload the 'public' folder contents to 'public' inside that directory.
 * 5. Set this 'server.js' as the application entry point in Hostinger panel.
 */

// Set production environment
process.env.NODE_ENV = 'production';

// Port is typically provided by Hostinger via environment variable
const port = process.env.PORT || 3000;
process.env.PORT = port;

// Next.js standalone server entry
// Note: When using 'output: standalone', Next.js creates a server.js in .next/standalone
// We require it here. If you upload the standalone folder contents to root, use path.join(__dirname, 'server.js')
// If you keep the structure, use path.join(__dirname, '.next', 'standalone', 'server.js')

try {
  // Try to load the standalone server
  // Assuming the user followed the standard standalone deployment pattern
  require('./server.js'); 
} catch (e) {
  console.error('Next.js standalone server not found. Please ensure you have run "npm run build" and uploaded the standalone output.');
  console.error(e);
}
